# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id_env:
    parameters:
      id:
        type: string
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

  print_pipeline_id_param:
    steps:
      - run: echo << parameters.id >>

# Orchestrate or schedule a set of jobs
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  my_job_env:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id_env      

  my_job_param:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id_param:
          id: << pipeline.id >>   
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello

  test-env-vars:
    jobs:
      - build

  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output

  my_reusable_workflow:
    jobs:
      - my_job_env
      - my_job_param            